/* Generated by gliss-csim ($(date)) copyright (c) 2024 IRIT - UPS */

#include <stdio.h>
#include <stdlib.h>
#include <csim.h>
#include "csim-rt.h"

#define ____COMP_NUM		(inst->number)

/* useful macros */
#define __now 		inst->board->date
#define ____VALUE	val

/* register accessors */
$(foreach registers)
#define _$(NAME)	__inst->$(name)
$(end)

/* port accessors */
$(foreach ports)
#define _$(name)	__inst->$(name)
$(end)

/* port bases */
$(foreach ports)
#define $(name)_BASE	$(base)
$(end)

/* port macros */
$(foreach ports)
#	define $(name)_PORT	&ports[$(name)_BASE]
	$(if multiple)
#		define $(name)_SET(i, x)	\
			{ \
				if(_$(name)[i] != x) { \
					_$(name)[i] = x; \
					csim_send_digital(inst, $(name)_PORT + i, _$(name)[i]); \
				} \
			}
	$(else)
#		define $(name)_SET(x)	\
			{ \
				if(x != _$(name)) { \
					_$(name) = x; \
					csim_send_digital(inst, $(name)_PORT, _$(name)); \
				} \
			}
	$(end)
$(end)




/**
 * Instance definition.
 */
typedef struct  $(comp)_inst_t {
	$(if io_comp)
    csim_iocomp_t inst;
	$(else)
	csim_inst_t inst;
	$(end)

	/* registers */
    $(foreach registers)
	$(if multiple)
	$(type) $(name)[$(size)];
	$(else)
	$(type) $(name);
	$(end)
    $(end)
	/* ports */
    $(foreach ports)
	$(if multiple)
	$(ctype) $(name)[$(count)];
	$(else)
	$(ctype) $(name);
	$(end)
	$(end)
}  $(comp)_inst_t;


/* pre-definitiion of callbacks */
$(foreach ports)
static void on_update_$(name)(csim_inst_t *inst);
$(end)
$(foreach events)
static void on_update_$(name)(csim_inst_t *inst);
$(end)
$(foreach events)
static void on_trigger_$(name)(csim_evt_t *evt);
$(end)

$(foreach registers)
$(if !intern)
/* $(name) register functions */

static void name_$(name)(csim_inst_t *inst, int num, char *__buffer, int size) {
	$(comp)_inst_t *__inst = ($(comp)_inst_t *)inst;
	$(label)
}

static void display_$(name)(csim_inst_t *inst, int num, char *__buffer, int size) {
	$(comp)_inst_t *__inst = ($(comp)_inst_t *)inst;
	$(display);
}

static csim_word_t read_$(name)(csim_inst_t *inst, int num) {
$(if is_read_only)
	csim_log(inst->board, CSIM_WARN, "read of ${comp}.${name} that is read-only");
	return 0;
$(else)
	$(comp)_inst_t *__inst = ($(comp)_inst_t *)inst;
$(ifdef on_read)
	$(on_read);
$(end)
	return __inst->$(name)$(if multiple)[num]$(end);
$(end)
}

static void write_$(name)(csim_inst_t *inst, int num, csim_word_t val) {
	$(comp)_inst_t *__inst = ($(comp)_inst_t *)inst;
$(ifdef on_write)$(on_write)$(end)
	int updated = val != _$(NAME)$(if multiple)[num]$(end);
	_$(NAME)$(if multiple)[num]$(end) = val;
$(if update_on_write)
	if(updated)
		csim_wakeup(inst);
$(end)
}

static csim_word_t get_$(name)(csim_inst_t *inst, int num) {
	$(comp)_inst_t *__inst = ($(comp)_inst_t *)inst;
	return __inst->$(name)$(if multiple)[num]$(end);
}

static void set_$(name)(csim_inst_t *inst, int num, csim_word_t val) {
	$(comp)_inst_t *__inst = ($(comp)_inst_t *)inst;
	__inst->$(name)$(if multiple)[num]$(end) = val;
}


$(end)
$(end)


/**
 * Array of registers.
 */
static csim_reg_t regs[] = {
	$(foreach registers)
	{
		"$(name)",		// name
		$(offset),		// offset
		$(size),		// size
		$(count),		// count
		$(stride),		// stride
		0,				// flags
		$(ctype),		// signal type
		$(if !intern)
		name_$(name),
		display_$(name),
		read_$(name),
		write_$(name),
		get_$(name),
		set_$(name)
		$(end)
	},
	$(end)
};


/* predeclaration of port-functions */
$(foreach ports)
static void on_input_$(name)(csim_port_inst_t *port, csim_value_type_t type, csim_value_t val);
$(end)


/**
 * Array of ports.
 */
static csim_port_t ports[] = {
$(foreach ports)
$(if multiple)
$(foreach indexes)
	{
		"$(label)",
		$(type),
		on_input_$(name)
	},
$(end)
$(else)
	{
		"$(name)",
		$(type),
		on_input_$(name)
	},
$(end)
$(end)
};


$(foreach ports)
/* $(name) port functions */

static void on_input_$(name)(csim_port_inst_t *port, csim_value_type_t type, csim_value_t value) {
	int val = value.digital;
	csim_inst_t *inst = port->inst;
	$(comp)_inst_t *__inst = ($(comp)_inst_t *)inst;
	$(if multiple)	int ____INDEX = port - port->inst->ports - $(name)_BASE;$(end)

	if(val != _$(name)$(if multiple)[____INDEX]$(end)) {
		_$(name)$(if multiple)[____INDEX]$(end) = val;
		$(on_input)
$(if update_on_input)
		csim_wakeup(port->inst);
$(end)
	}
}

$(end)

$(foreach events)
/* $(name) event functions */

static void on_update_$(name)(csim_inst_t *inst) {
	$(comp)_inst_t *__inst = ($(comp)_inst_t *)inst;
	$(on_update)
	$(if update_on_input)
		csim_wakeup(inst);
	$(end)
}

static void on_trigger_$(name)(csim_evt_t *evt) {
	$(comp)_inst_t *__inst = ($(comp)_inst_t *)evt->inst;
	csim_inst_t *inst = evt->inst;

	$(on_trigger)
}

$(end)


/**
 * Reset the instance.
 * @param inst	Instance to reset.
 */
static void  $(comp)_reset(csim_inst_t *inst) {
	$(comp)_inst_t *__inst = ( $(comp)_inst_t *)inst;
$(foreach registers)
$(if !multiple)
	_$(name) = $(init);
$(else)
	for(int i = 0; i < $(count); i++)
		_$(name)[i] = $(init);
$(end)
$(end)

$(foreach ports)
$(if !multiple)
	_$(name) = 0;
$(else)
	for(int i = 0; i < $(count); i++)
		_$(name)[i] = 0;
$(end)
$(end)
}

/**
 * Construct an instance.
 * @param inst	Instance to construct.
 */
static void $(comp)_construct(csim_inst_t *inst, csim_confs_t confs) {
	$(comp)_inst_t * $(comp)_inst = ( $(comp)_inst_t *)inst;
	$(comp)_reset(inst);
}

/**
 * Destruct the instance.
 * @param inst	Instance to destruct.
 */
static void $(comp)_destruct(csim_inst_t *inst) {
}

/**
 * Update the state of the component.
 * @param inst	Instance of the component.
 */
void $(comp)_update(csim_inst_t *inst) {
	$(comp)_inst_t *__inst = ( $(comp)_inst_t *)inst;
	$(update)
}

$(if io_comp)

static int $(comp)_display(char *buf, csim_iocomp_inst_t *inst) {
	char display[] = " ";
	// By default shows nothing, can be modified by changing the display var.
	return sprintf(buf,display);
}

static void $(comp)_on_key(char key, csim_iocomp_inst_t *inst) {
}


csim_iocomp_t  $(comp)_component = {
	{
    "$(comp)",
    CSIM_IO,
    0,					// version
    regs,				// registers
    $(register_count) ,	// register count
    ports,				// ports
    $(port_count),		// port count
    sizeof($(comp)_inst_t),
    $(comp)_construct,
    $(comp)_destruct,
    $(comp)_reset
	},
	$(comp)_display,
	$(comp)_on_key
};

$(else)
/**
 * $(comp) description structure.
 */
csim_component_t  $(arch)_$(comp)_component = {
	NULL,
    "$(arch)/$(comp)",
    CSIM_SIMPLE,		// type (TODO fix for IO comp)
    0,					// version
    regs,				// registers
    $(register_count) ,	// register count
    ports,				// ports
    $(port_count),		// port count
    sizeof($(comp)_inst_t),
    $(comp)_construct,
    $(comp)_destruct,
    $(comp)_reset,
    $(comp)_update
};
$(end)
