/* Generated by gliss-csim (126/06/18 15:39:06) copyright (c) 2026 IRIT - UPS */

#include "../csim.h"
$(foreach comps)
extern csim_component $(arch)_$(name)_component;
$(end)

static csim_component_t *$(arch)_components[] = {
	$(foreach comps)
		&$(arch)_$(name)_component.comp,
	$(end)
	NULL
};

csim_component_t **$(arch)_get_components() {
	return $(arch)_components;
}
